# NOTE: Make sure custom Reek configuration is saved before calling reek --todo
---
exclude_paths:
  - bin
  - db
  - node_modules
  - public
  - spec
  - vendor
detectors:
  FeatureEnvy:
    enabled: false
  IrresponsibleModule:
    enabled: false
  TooManyConstants:
    enabled: false
  UncommunicativeModuleName:
    enabled: false
  UncommunicativeVariableName:
    accept:
      - "e"
      - "_"
  UnusedParameters:
    exclude:
      - "BaseNormalizer#normalize"
      - "BaseProcessor#process"
  UtilityFunction:
    public_methods_only: true
