# This is a custom part of Reek configuration. Keep it in the top of .reek.yml,
# and make sure mentioned detectors are removed from the generated todo.
# Note: This file is NOT automatically applied to .reek.yml,
---
exclude_paths:
  - bin
  - node_modules
  - public
  - vendor
  - db
  - test
  - spec
detectors:
  IrresponsibleModule:
    enabled: false
  UncommunicativeModuleName:
    enabled: false
  UncommunicativeVariableName:
    accept:
      - "e"
      - "_"
  UtilityFunction:
    public_methods_only: true
  TooManyConstants:
    enabled: false
