require:
  - standard
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-factory_bot

inherit_gem:
  standard: config/base.yml
  standard-performance: config/base.yml

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  DisplayCopNames: true
  Exclude:
    - "bin/*"
    - "db/**/*"
    - "tmp/**/*"
    - "node_modules/**/*"
    - "vendor/bundle/**/*"

Style/RescueStandardError:
  EnforcedStyle: explicit

#
# Rails
#

Rails/SkipsModelValidations:
  Enabled: false

#
# RSpec
#

RSpec/ExampleLength:
  Max: 10

RSpec/MultipleMemoizedHelpers:
  Max: 10

RSpec/MultipleExpectations:
  Max: 3

RSpec/MessageSpies:
  Enabled: false
