inherit_mode:
  merge:
    - Exclude

require:
  - standard
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  DisplayCopNames: true
  Exclude:
    - "bin/*"
    - "db/**/*"
    - "node_modules/**/*"
    - "coverage"
    - "tmp"
    - "vendor/bundle/**/*"
