version: "3.8"

volumes:
  postgres:
  bundle:

services:
  app:
    build: .
    environment:
      - BUNDLE_PATH=/bundle
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/feeder_development
      - FREEFEED_BASE_URL
      - FREEFEED_TOKEN
      - HONEYBADGER_API_KEY=$FEEDER_HONEYBADGER_API_KEY
      - RAILS_ENV=development
      - RAILS_MASTER_KEY=$FEEDER_RAILS_MASTER_KEY
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY_BASE
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -p 3000 -b 0.0.0.0"
    ports:
      - 3000:3000
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
      - bundle:/bundle

  sh:
    build: .
    environment:
      - BUNDLE_PATH=/bundle
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/feeder_development
      - FREEFEED_BASE_URL
      - FREEFEED_TOKEN
      - HONEYBADGER_API_KEY=$FEEDER_HONEYBADGER_API_KEY
      - RAILS_ENV=development
      - RAILS_MASTER_KEY=$FEEDER_RAILS_MASTER_KEY
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY_BASE
    command: bash -c "bundle exec bash"
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
      - bundle:/bundle

  postgres:
    image: postgres:10
    environment:
      POSTGRES_DB: feeder_development
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      PGDATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - 6379
