version: "3.8"

volumes:
  postgres:
  bundle:

services:
  app:
    build: .
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/feeder_development
      BUNDLE_PATH: /bundle
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -p 3000 -b 0.0.0.0"
    ports:
      - 3000:3000
    depends_on:
      - postgres
    volumes:
      - .:/app
      - bundle:/bundle

  postgres:
    image: postgres:10
    environment:
      POSTGRES_DB: feeder_development
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      PGDATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  test:
    build: .
    environment:
      RAILS_ENV: test
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/feeder_test?pool=5
      BUNDLE_PATH: /bundle
      DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL: "true"
    command: bundle exec rails test
    depends_on:
      - postgres
    volumes:
      - .:/app
      - bundle:/bundle
