version: '3'
services:
  feederapp:
    build:
      context: .
      dockerfile: docker/DockerFile
      args:
        RACK_ENV: development
        RAILS_ENV: development
        DATABASE_URL: postgresql://user:password@db:5432/myapp_development?pool=5
    container_name: feederapp-container
    command: bash -c "bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
      - "3035:3035"
    depends_on:
      - db
    networks:
      - feedernetwork
  db:    
    image: postgres:9.6
    ports:
      - "5432:5432"
    container_name: feederdb-container
    environment:
      POSTGRES_DB: myapp_development
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
    networks:
      - feedernetwork
networks:
      feedernetwork:
          driver: bridge