version: "3.8"

volumes:
  postgres:
  bundle:

services:
  app:
    build: .
    environment:
      RACK_ENV: development
      RAILS_ENV: development
      DATABASE_URL: postgresql://postgres:postgres@db:5432/feeder_development?pool=5
      WEBPACKER_DEV_SERVER_HOST: webpacker
      BUNDLE_PATH: /bundle
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -p 3000 -b 0.0.0.0"
    ports:
      - 3000:3000
    depends_on:
      - db
      - webpacker
    volumes:
      - .:/app
      - bundle:/bundle

  db:
    image: postgres:10
    environment:
      POSTGRES_DB: feeder_development
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      PGDATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  webpacker:
    build: .
    environment:
      NODE_ENV: development
      RAILS_ENV: development
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
      BUNDLE_PATH: /bundle
    command: ./bin/webpack-dev-server
    volumes:
      - .:/app
      - bundle:/bundle
    ports:
      - 3035:3035

  runner:
    build: .
    environment:
      RACK_ENV: development
      RAILS_ENV: development
      DATABASE_URL: postgresql://postgres:postgres@db:5432/feeder_development?pool=5
      WEBPACKER_DEV_SERVER_HOST: webpacker
      BUNDLE_PATH: /bundle
    command: bash
    depends_on:
      - db
    volumes:
      - .:/app
      - bundle:/bundle
