version: "3.8"

volumes:
  postgres:
  bundle:

services:
  app:
    build: .
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/app_development
      BUNDLE_PATH: /bundle
      REDIS_URL: redis://redis:6379/0
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -p 3000 -b 0.0.0.0"
    ports:
      - 3000:3000
    depends_on:
      - postgres
      # - redis
    volumes:
      - .:/app
      - bundle:/bundle

  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: app_development
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      PGDATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  # redis:
  #   image: redis:6
  #   command: redis-server
  #   ports:
  #     - 6379:6379

  test:
    build: .
    environment:
      RAILS_ENV: test
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/feeder_test?pool=5
      BUNDLE_PATH: /bundle
      DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL: true
      REDIS_URL: redis://redis:6379/1
    command: bundle exec rspec
    depends_on:
      - postgres
      # - redis
    volumes:
      - .:/app
      - bundle:/bundle
