FROM ruby:2.6.5

RUN curl https://deb.nodesource.com/setup_10.x | bash
RUN curl https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list

RUN apt-get update && apt-get install -y nodejs yarn

# Setting up the environment
ARG RACK_ENV
ARG RAILS_ENV
ARG DATABASE_URL
ENV RAILS_ENV=$RAILS_ENV
ENV RACK_ENV=$RACK_ENV
ENV DATABASE_URL=$DATABASE_URL

RUN mkdir /feeder_app 
WORKDIR /feeder_app 

COPY Gemfile /feeder_app/Gemfile
RUN bundle install

COPY package.json /feeder_app/package.json
COPY yarn.lock /feeder_app/yarn.lock
RUN yarn install

COPY . /feeder_app