development:
  adapter: postgresql
  url: <%= Rails.application.credentials.database_url %>

test:
  adapter: postgresql
  url: <%= Rails.application.credentials.database_url %>

production:
  adapter: postgresql
  url: <%= Rails.application.credentials.database_url %>
