development:
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>

test:
  adapter: postgresql
  url: <%= Rails.application.credentials.database_url %>

production:
  adapter: postgresql
  url: <%= Rails.application.credentials.database_url %>
