development:
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] || Rails.application.credentials.database_url %>

test:
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] || Rails.application.credentials.database_url %>

production:
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] || Rails.application.credentials.database_url %>
