development:
  adapter: postgresql
  url: <%= ENV.fetch("DATABASE_URL") %>

test:
  adapter: postgresql
  url: <%= ENV.fetch("DATABASE_URL") %>

production:
  adapter: postgresql
  url: <%= ENV.fetch("DATABASE_URL") %>
