import {
  LOAD_FEED,
  LOAD_FEED_PENDING,
  LOAD_FEED_FULFILLED,
  LOAD_FEED_REJECTED
} from 'main/actions/loadFeed'

import {
  LOAD_FEEDS,
  LOAD_FEEDS_PENDING,
  LOAD_FEEDS_FULFILLED,
  LOAD_FEEDS_REJECTED
} from 'main/actions/loadFeeds'

import {
  LOAD_ACTIVITY,
  LOAD_ACTIVITY_PENDING,
  LOAD_ACTIVITY_FULFILLED,
  LOAD_ACTIVITY_REJECTED
} from 'main/actions/loadActivity'

import {
  LOAD_POSTS,
  LOAD_POSTS_PENDING,
  LOAD_POSTS_FULFILLED,
  LOAD_POSTS_REJECTED
} from 'main/actions/loadPosts'

import {
  LOAD_UPDATES,
  LOAD_UPDATES_PENDING,
  LOAD_UPDATES_FULFILLED,
  LOAD_UPDATES_REJECTED
} from 'main/actions/loadUpdates'

import {
  LOAD_FEED_ACTIVITY,
  LOAD_FEED_ACTIVITY_PENDING,
  LOAD_FEED_ACTIVITY_FULFILLED,
  LOAD_FEED_ACTIVITY_REJECTED
} from 'main/actions/loadFeedActivity'

import {
  LOAD_FEED_POSTS,
  LOAD_FEED_POSTS_PENDING,
  LOAD_FEED_POSTS_FULFILLED,
  LOAD_FEED_POSTS_REJECTED
} from 'main/actions/loadFeedPosts'

import {
  LOAD_FEED_UPDATES,
  LOAD_FEED_UPDATES_PENDING,
  LOAD_FEED_UPDATES_FULFILLED,
  LOAD_FEED_UPDATES_REJECTED
} from 'main/actions/loadFeedUpdates'

import {
  LOAD_BATCHES,
  LOAD_BATCHES_PENDING,
  LOAD_BATCHES_FULFILLED,
  LOAD_BATCHES_REJECTED
} from 'main/actions/loadBatches'

export const rejections = {
  [LOAD_FEED_REJECTED]: LOAD_FEED,
  [LOAD_FEEDS_REJECTED]: LOAD_FEEDS,
  [LOAD_ACTIVITY_REJECTED]: LOAD_ACTIVITY,
  [LOAD_POSTS_REJECTED]: LOAD_POSTS,
  [LOAD_UPDATES_REJECTED]: LOAD_UPDATES,
  [LOAD_FEED_ACTIVITY_REJECTED]: LOAD_FEED_ACTIVITY,
  [LOAD_FEED_POSTS_REJECTED]: LOAD_FEED_POSTS,
  [LOAD_FEED_UPDATES_REJECTED]: LOAD_FEED_UPDATES,
  [LOAD_BATCHES_REJECTED]: LOAD_BATCHES
}

export const pendings = {
  [LOAD_FEED_PENDING]: LOAD_FEED,
  [LOAD_FEEDS_PENDING]: LOAD_FEEDS,
  [LOAD_ACTIVITY_PENDING]: LOAD_ACTIVITY,
  [LOAD_POSTS_PENDING]: LOAD_POSTS,
  [LOAD_UPDATES_PENDING]: LOAD_UPDATES,
  [LOAD_FEED_ACTIVITY_PENDING]: LOAD_FEED_ACTIVITY,
  [LOAD_FEED_POSTS_PENDING]: LOAD_FEED_POSTS,
  [LOAD_FEED_UPDATES_PENDING]: LOAD_FEED_UPDATES,
  [LOAD_BATCHES_PENDING]: LOAD_BATCHES,
}

export const fulfillments = {
  [LOAD_FEED_FULFILLED]: LOAD_FEED,
  [LOAD_FEEDS_FULFILLED]: LOAD_FEEDS,
  [LOAD_ACTIVITY_FULFILLED]: LOAD_ACTIVITY,
  [LOAD_POSTS_FULFILLED]: LOAD_POSTS,
  [LOAD_UPDATES_FULFILLED]: LOAD_UPDATES,
  [LOAD_FEED_ACTIVITY_FULFILLED]: LOAD_FEED_ACTIVITY,
  [LOAD_FEED_POSTS_FULFILLED]: LOAD_FEED_POSTS,
  [LOAD_FEED_UPDATES_FULFILLED]: LOAD_FEED_UPDATES,
  [LOAD_BATCHES_FULFILLED]: LOAD_BATCHES
}
