name: release

on:
  push:
    branches:
      - chore/ansible

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Lint Ansible playbook
        uses: ansible-community/ansible-lint-action@v6.0.2
        with:
          args: "ansible"

      - name: Run Ansible playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: ./ansible/test.yml
          directory: ./ansible

          # Optional, SSH private key
          # key: ${{secrets.SSH_PRIVATE_KEY}}

          # Optional, literal inventory file contents
          inventory: |
            [all]
            $PRODUCTION_HOST

          known_hosts: |
            $PRODUCTION_HOST ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBKSNFUaFj5lPqrrdbqGGMUeUUHf/su6Iw7zzWCwXHPeSFlS+PPtaCkyzcNqH/gSMST4XBLVgXECEtY/ORyiE/zo=
            $PRODUCTION_HOST ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDCgl9mcdOj5UAuye2qvreM6u8rvt8QWPBwxpuQe5uxh5Kx0fxHjeuGY5i16v1qt7jqbesXavZ+hKzRttxk9mGpktgbm86TCZug74N3BpGPRZFADXyYCtUje29hj1Nqoea1D0If/c/e1q43X3zrG8bJdJ/PJUJNijjIntDjFLCm632QxRb6gbKxUhFpEdWvmim4t0q6BI6/Xx2oChA4r1T31ysaDYhg5k90W/+A78uqHLFucBiOv7xoxNkqJksEV4HtkDvPmrIK1Ah/wAg2LNGJMc3kNOX6KTdKt6FN5g8Iw+C4SZdl/xfZH7s7eAOHfs/khd1J+aPQJUtbMGW68WX7
            $PRODUCTION_HOST ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILcWHJsIFihpt/BDehUvSgL4NdZH6riQ+RiSSJa0f2a5

          # Optional, encrypted vault password
          # vault_password: ${{secrets.VAULT_PASSWORD}}

          # Optional, galaxy requirements filepath
          # requirements: galaxy-requirements.yml

          # Optional, additional flags to pass to ansible-playbook
          options: |
            --inventory .hosts
            --limit all
            --extra-vars hello=there
            --verbose
